# Generated by Django 3.0 on 2019-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KNDhistor',
            fields=[
                ('date', models.CharField(help_text='Дата отчета.', max_length=20, primary_key=True, serialize=False, verbose_name='Дата')),
                ('day', models.IntegerField(help_text='День.', verbose_name='День')),
                ('month', models.IntegerField(help_text='Месяц.', verbose_name='Месяц')),
                ('year', models.IntegerField(help_text='Год.', verbose_name='Год')),
                ('maxdvor', models.IntegerField(help_text='Всего дворов.', verbose_name='Всего дворов')),
                ('complete', models.IntegerField(help_text='Выполнено дворов.', verbose_name='Выполнено дворов')),
                ('proc', models.IntegerField(help_text='Процент выполнения.', verbose_name='Процент выполнения')),
                ('times', models.CharField(help_text='Время отчета.', max_length=20, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Отчеты по осмотру территорий',
                'ordering': ['year', 'month', 'day'],
            },
        ),
    ]
