# Generated by Django 3.0 on 2019-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIPhistor',
            fields=[
                ('date', models.CharField(help_text='Дата отчета.', max_length=20, primary_key=True, serialize=False, verbose_name='Дата')),
                ('day', models.IntegerField(help_text='День.', verbose_name='День')),
                ('month', models.IntegerField(help_text='Месяц.', verbose_name='Месяц')),
                ('year', models.IntegerField(help_text='Год.', verbose_name='Год')),
                ('maxdvor', models.IntegerField(help_text='Всего ДИП.', verbose_name='Всего ДИП')),
                ('complete', models.IntegerField(help_text='Выполнено ДИП.', verbose_name='Выполнено ДИП')),
                ('proc', models.IntegerField(help_text='Процент ДИП.', verbose_name='Процент ДИП')),
                ('times', models.CharField(help_text='Время отчета.', max_length=20, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Отчеты по осмотру ДИП',
                'ordering': ['year', 'month', 'day'],
            },
        ),
    ]
