# Generated by Django 3.0 on 2019-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_diphistor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersbot',
            fields=[
                ('username', models.CharField(help_text='username', max_length=20, verbose_name='username')),
                ('id', models.IntegerField(help_text='ID пользователя.', primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия', max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, help_text='Имя', max_length=20, verbose_name='Имя')),
                ('uuid', models.CharField(help_text='uuid регистрации', max_length=35, verbose_name='uuid')),
                ('status', models.CharField(help_text='Статус регистрации', max_length=20, verbose_name='Статус')),
                ('role', models.CharField(help_text='Роль пользователя', max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'пользователь бота',
                'verbose_name_plural': 'пользователи бота',
                'ordering': ['username'],
            },
        ),
        migrations.AlterModelOptions(
            name='diphistor',
            options={'ordering': ['year', 'month', 'day'], 'verbose_name': 'отчет по осмотру ДИП', 'verbose_name_plural': 'отчеты по осмотру ДИП'},
        ),
        migrations.AlterModelOptions(
            name='kndhistor',
            options={'ordering': ['year', 'month', 'day'], 'verbose_name': 'отчет по осмотру территорий', 'verbose_name_plural': 'отчеты по осмотру территорий'},
        ),
        migrations.AlterField(
            model_name='kndhistor',
            name='times',
            field=models.CharField(help_text='Время отчета.', max_length=20, verbose_name='Время проверки'),
        ),
    ]
