# Generated by Django 3.0 on 2019-12-18 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_usersbot_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
