# Generated by Django 3.0 on 2019-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_mkdhistor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kndhistor',
            name='maxdvor',
        ),
        migrations.RemoveField(
            model_name='kndhistor',
            name='proc',
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='completeproc',
            field=models.IntegerField(default=3, help_text='Выполнено процентов.', verbose_name='Выполнено процентов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='dost',
            field=models.IntegerField(default=3, help_text='Доступно.', verbose_name='Доступно'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='dostproc',
            field=models.IntegerField(default=3, help_text='Доступно процентов.', verbose_name='Доступно процентов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='netreb',
            field=models.IntegerField(default=3, help_text='Не ребуются.', verbose_name='Не ребуются'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='netrebproc',
            field=models.IntegerField(default=3, help_text='Не ребуются процентов.', verbose_name='Не ребуются процентов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='vrabote',
            field=models.IntegerField(default=3, help_text='В работе.', verbose_name='В работе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kndhistor',
            name='vraboteproc',
            field=models.IntegerField(default=3, help_text='В работе процентов.', verbose_name='В работе процентов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='complete',
            field=models.IntegerField(help_text='Выполнено осмотров.', verbose_name='Выполнено осмотров'),
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='proc',
            field=models.IntegerField(help_text='Процент выполнения.', verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='kndhistor',
            name='complete',
            field=models.IntegerField(help_text='Выполнено.', verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='mkdhistor',
            name='complete',
            field=models.IntegerField(help_text='Выполнено осмотров.', verbose_name='Выполнено осмотров'),
        ),
        migrations.AlterField(
            model_name='mkdhistor',
            name='proc',
            field=models.IntegerField(help_text='Процент выполнения.', verbose_name='Процент выполнения'),
        ),
    ]
