# Generated by Django 3.0 on 2019-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20191223_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diphistor',
            name='day',
            field=models.IntegerField(blank=True, help_text='День.', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='month',
            field=models.IntegerField(blank=True, help_text='Месяц.', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='year',
            field=models.IntegerField(blank=True, help_text='Год.', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='kndhistor',
            name='day',
            field=models.IntegerField(blank=True, help_text='День.', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='kndhistor',
            name='month',
            field=models.IntegerField(blank=True, help_text='Месяц.', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='kndhistor',
            name='year',
            field=models.IntegerField(blank=True, help_text='Год.', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='mkdhistor',
            name='day',
            field=models.IntegerField(blank=True, help_text='День.', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='mkdhistor',
            name='month',
            field=models.IntegerField(blank=True, help_text='Месяц.', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='mkdhistor',
            name='year',
            field=models.IntegerField(blank=True, help_text='Год.', verbose_name='Год'),
        ),
    ]
