# Generated by Django 3.0 on 2019-12-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20191223_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='kndhistor',
            name='allz',
            field=models.IntegerField(default=1, help_text='Всего задач.', verbose_name='Всего задач'),
            preserve_default=False,
        ),
    ]
