# Generated by Django 3.0 on 2019-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_kndhistor_allz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konfbot',
            fields=[
                ('id', models.IntegerField(help_text='ID конференции.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название конференции', max_length=20, verbose_name='Название конференции')),
                ('status', models.CharField(default='0', help_text='Статус регистрации', max_length=20, verbose_name='Статус')),
                ('role', models.CharField(default='444', help_text='Роль пользователя', max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'пользователь бота',
                'verbose_name_plural': 'пользователи бота',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='email',
            field=models.EmailField(blank=True, help_text='Почта', max_length=40, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='role',
            field=models.CharField(default='244', help_text='Роль пользователя', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='status',
            field=models.CharField(default='0', help_text='Статус регистрации', max_length=20, verbose_name='Статус'),
        ),
    ]
