# Generated by Django 3.0 on 2019-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20191223_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konfbot',
            options={'ordering': ['id'], 'verbose_name': 'конференция бота', 'verbose_name_plural': 'конференции бота'},
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
