# Generated by Django 3.0 on 2019-12-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20191223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diphistor',
            name='day',
            field=models.IntegerField(blank=True, help_text='День.', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='month',
            field=models.IntegerField(blank=True, help_text='Месяц.', null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='diphistor',
            name='year',
            field=models.IntegerField(blank=True, help_text='Год.', null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='konfbot',
            name='role',
            field=models.CharField(default='000', help_text='Роль пользователя', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='usersbot',
            name='role',
            field=models.CharField(default='100', help_text='Роль пользователя', max_length=20, verbose_name='Роль'),
        ),
    ]
